### ISSUE TITLE
Feature: User can read information regarding Studio Ghibli films, characters, species and locations.

### ISSUE THREAD

**Issue by dxnielperez** [Daniel-PerezF/Studio-Ghibli-Wiki#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> User can view a list of Studio Ghibli films with related information to each film as well as view an about page with the history of Studio Ghibli.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-10-02 at 11 08 58 AM](https://github.com/Daniel-PerezF/ajax-project/assets/127264112/7df116a1-4e91-40bc-9f64-f75494802af5)
![Screen Shot 2023-10-02 at 11 09 06 AM](https://github.com/Daniel-PerezF/ajax-project/assets/127264112/10c47672-417c-475c-bedd-c7644565a2fa)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Write html layout for the films/home page.
     - [x] Write css for mobile first.
- [x] Write html for about page.
     - [x] Write css for mobile first.
- [x] Create drop down modal when menu button is clicked on.
     - [x] Modal should include About, Films, Favorites and Watchlist.
- [x] Add event listener to "About" that view swaps to the about page when clicked.
- [x] Add event listener to "Films" that view swaps to the films/home page when clicked.
     - [x] Add css for mobile first.
- [x] Create view swap when film cards are clicked on to show full information page.
     - [x] Populate fields with API information.
- [x]  Make Responsive for desktop
- [x] Add last css styling
- **Clean Up**
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
