### ISSUE TITLE
Feature: User can favorite films.

### ISSUE THREAD

**Issue by dxnielperez** [Daniel-PerezF/Studio-Ghibli-Wiki#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click the "favorite" icon and that specific film along with the information will be added to a favorites list
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-10-05 at 10 07 45 AM](https://github.com/Daniel-PerezF/Studio-Ghibli-Wiki/assets/127264112/e1be574e-1e49-47c4-a931-8f041435f1ce)
![Screen Shot 2023-10-05 at 10 07 45 AM](https://github.com/Daniel-PerezF/Studio-Ghibli-Wiki/assets/127264112/a2721cac-f0ed-4631-860c-ecfe29982e18)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a separate html view for the favorited items to be added to later.
- [x] Create a dummy favorite entry to match the entry in the films page.
- [x] Create styling for mobile first.
- [x] Create a function that represents the object that was favorited.The function adds the favorited item to local storage to create the DOM later.
- [x] Create an event listener on the favorite button to add items to localstorage.
- [x] Remove the example entry from html once users favorites are successfully being appended to the favorites view.
- [x] Create a function that toggles "No films have been added" when the function is called.
- [x] Update the favorite button to do the following:
     - [x] Renders the DOM tree using the created function .
     - [x] Prepends the new DOM tree to the favorites page.
     - [x] Conditionally toggles "no films have been added" as needed.
     
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
