### ISSUE TITLE
Feature: User can delete favorites

### ISSUE THREAD

**Issue by dxnielperez** [Daniel-PerezF/Studio-Ghibli-Wiki#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete films from their favorites
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-10-06 at 2 38 53 PM](https://github.com/Daniel-PerezF/Studio-Ghibli-Wiki/assets/127264112/a6763e12-2e8b-4e7c-b577-9f4dfe31ed8d)
![Screen Shot 2023-10-06 at 2 39 05 PM](https://github.com/Daniel-PerezF/Studio-Ghibli-Wiki/assets/127264112/7892c1a4-c588-412b-b3c6-8e5e1896cadb)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a button to the favorites card with the text "remove from favorites".
- [x] Add event listener to "remove" button.
- [x] Create a function that when the "remove"  button is clicked will :
     - [x]  Remove the corresponding item from the data model array.
     - [x]  Remove the corresponding item from the DOM.
     - [x] Conditionally toggle no entries function if necessary.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
