### ISSUE TITLE
Feature: User can create a watch list.

### ISSUE THREAD

**Issue by dxnielperez** [Daniel-PerezF/Studio-Ghibli-Wiki#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can create a watchlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-10-08 at 2 28 50 PM](https://github.com/Daniel-PerezF/Studio-Ghibli-Wiki/assets/127264112/2c35dafc-6f33-4833-b674-689d5c535fb4)
![Screen Shot 2023-10-08 at 2 29 58 PM](https://github.com/Daniel-PerezF/Studio-Ghibli-Wiki/assets/127264112/1862dffb-b54f-40b3-bd39-512969a20b3b)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a separate html view for the watchlist items to be added to later.
- [x] Create a dummy watchlist entry to match the entry in the films page.
- [x] Create styling for mobile first.
- [x] Add event listener to watchlist on the menu that view swaps to the watchlist page.
- [x] Create a function that represents the object that was added to watchlist. The function adds the item to local storage to create the DOM later.
- [x] Create an event listener on the bookmark button to add items to the data model which will later be added to localstorage.
- [x] Remove the example entry from html once the user watchlist are successfully being appended to the watchlist view.
- [x] Create a function that toggles "No films have been added" when the function is called.
- [x] Update the bookmark button to do the following:
     - [x] Renders the DOM tree using the created function .
     - [x] Prepends the new DOM tree to the watchlist page.
     - [x] Conditionally toggles "no films have been added" as needed.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
