### ISSUE TITLE
Feature: User can delete items from their watchlist.

### ISSUE THREAD

**Issue by dxnielperez** [Daniel-PerezF/Studio-Ghibli-Wiki#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete items from their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the "remove" button to remove items from their watchlist.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-10-09 at 10 30 40 AM](https://github.com/Daniel-PerezF/Studio-Ghibli-Wiki/assets/127264112/8407df22-1c3b-4a60-9181-5efa717fdd56)
![Screen Shot 2023-10-09 at 10 30 53 AM](https://github.com/Daniel-PerezF/Studio-Ghibli-Wiki/assets/127264112/07844926-cdf0-4a6e-af55-a199b603937a)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add event listener to "remove" button.
- [x] Create a function that when the "remove"  button is clicked will :
     - [x]  Remove the corresponding item from the data model array.
     - [x]  Remove the corresponding item from the DOM.
     - [x] Conditionally toggle no entries function if necessary.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
